services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4 #7.17.0 #7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4 #7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME_FOR_KIBANA}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD_FOR_KIBANA}
      # - ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN=${ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN}
      - ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY=${ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY}
      - REPORTING_ENCRYPTION_KEY=${REPORTING_ENCRYPTION_KEY}
      - SECURITY_ENCRYPTION_KEY=${SECURITY_ENCRYPTION_KEY}
    links:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

  filebeat:
    build:
        context: ./filebeat
    container_name: filebeat
    volumes:
        - ./fastapi-logs:/src/logs
    depends_on:
        - elasticsearch
        - kibana
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME_FOR_FILEBEAT}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD_FOR_FILEBEAT}

    networks:
      - elastic

  fastapi:
    build:
      context: ./fastapi-app 
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - elasticsearch
    volumes:
        - ./fastapi-logs:/src/logs

volumes:
    elasticsearch_data:
        driver: local
    esdata:
      name: esdata

networks:
  elastic:
    driver: bridge